Feat:versioning API
hngx-org/spitfire-super-admin-one pull request #197
Opened 2023-10-20 12:44 UTC by Freeman-kuch

- ​Versioned all API endpoints 
- pluralized endpoints form singular references to plural 

## Description

​- ​Versioned all API endpoints from `/api/admin/product` to `/api/admin/v1/product`
- pluralized endpoints form singular references to plural `/api/admin/v1/products` and so on
- 

​
## Motivation and Context

​Boss @zxenonx  ordered it be done!

## How Has This Been Tested?

​- all refactored endpoints were tested using postman

## Screenshots (if appropriate - Postman, etc):
![Uploading Screenshot (27).png…]()
![Screenshot (28)](https://github.com/hngx-org/spitfire-super-admin-one/assets/105496324/a15a3619-9127-48a9-ba55-3d9b371a604a)
![Screenshot (29)](https://github.com/hngx-org/spitfire-super-admin-one/assets/105496324/d029f774-6ec7-4635-b9de-ba11ca913f55)
![Screenshot (30)](https://github.com/hngx-org/spitfire-super-admin-one/assets/105496324/770e9c21-dd16-46ba-bc39-1f50958a03bf)
![Screenshot (31)](https://github.com/hngx-org/spitfire-super-admin-one/assets/105496324/c2a40f93-e8a7-4325-8be2-a996df98ffd5)

​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-10-20 12:45 UTC, Freeman-kuch commented
@zxenonx

2023-10-20 15:42 UTC, zxenonx requested changes
Thanks @Freeman-kuch 
I left some comments.

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/products/routes.py
>  def approve_product(user_id, product_id):  #FOR SANCTIONED PRODUCTS
docstring missing

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/products/routes.py
>  def permanent_delete(user_id, product_id):
docstring missing

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
>  def total_shop_sales(user_id) -> defaultdict:
type hint and docstring missing

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
> +@shop.route("/banned-vendors", methods=["GET"])
```suggestion
@shop.route("/vendors?status=banned", methods=["GET"])
```

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
>  def get_banned_vendors(user_id):
type hint and docstring missing

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
> +@shop.route("/unban-vendors/<vendor_id>", methods=["PUT"])
```suggestion
@shop.route("/vendors/<vendor_id>/unban", methods=["PUT"])
```

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
>  def unban_vendor(user_id, vendor_id):
type hint and docstring missing

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
> +@shop.route("delete-shop/<shop_id>", methods=["PATCH"])
check soft delete suggestion above

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
>  def delete_shop(user_id, shop_id):
type hint and docstring missing

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
> +@shop.route("delete-shop/<shop_id>", methods=["DELETE"])
```suggestion
@shop.route("shops/<shop_id>", methods=["DELETE"])
```

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
>  def perm_del(user_id, shop_id):
- permanent_delete

- type hint and docstring missing

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
> +@shop.route("/temporarily-deleted-vendors", methods=["GET"])
```suggestion
@shop.route("/vendors?status=soft-deleted", methods=["GET"])
```

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
>  def get_temporarily_deleted_vendors(user_id):
type hint and docstring missing

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
> +@shop.route("/temporarily-deleted-vendor/<string:vendor_id>",  methods=["GET"])
```suggestion
@shop.route("/vendors/<string:vendor_id>?status=soft-deleted",  methods=["GET"])
```

2023-10-20 15:42 UTC, zxenonx commented on super_admin_1/shop/routes.py
>  def get_temporarily_deleted_vendor(user_id, vendor_id):
type hint and docstring missing

2023-10-20 15:47 UTC, Freeman-kuch commented on super_admin_1/products/routes.py
>  def get_product_statistics(user_id):
where ? for the user_id?

2023-10-20 15:54 UTC, zxenonx commented on super_admin_1/products/routes.py
>  def get_product_statistics(user_id):
Yes

2023-10-20 15:55 UTC, zxenonx commented on super_admin_1/products/routes.py
>  def get_product_statistics(user_id):
Type hints for all function parameters

2023-10-20 16:23 UTC, Freeman-kuch commented on super_admin_1/shop/routes.py
> +@shop.route("/banned-vendors", methods=["GET"])
this route would most likely be edprecated, its not actually being used

the shops/all endpoint handles it

2023-10-20 16:29 UTC, Freeman-kuch commented on super_admin_1/products/routes.py
>  def get_product_statistics(user_id):
ok boss

2023-10-20 16:30 UTC, Freeman-kuch commented on super_admin_1/products/routes.py
> +@product.route("/restore-products/<product_id>", methods=["PATCH"])
alriight boss

2023-10-20 17:03 UTC, Freeman-kuch commented on super_admin_1/products/routes.py
> +@product.route("delete-products/<product_id>", methods=["PATCH"])
oh, thanks, just read through and actually understand what they are saying

2023-10-20 17:42 UTC, Freeman-kuch commented on super_admin_1/products/routes.py
> +@product.route("/temporarily-deleted-products", methods=["GET"], strict_slashes=False)
removing the route totally, theres a filter taking care of it

2023-10-20 18:03 UTC, Freeman-kuch commented on super_admin_1/shop/routes.py
> +@shop.route("/banned-vendors", methods=["GET"])
removed the endpoint entirely

2023-10-20 18:53 UTC, Freeman-kuch commented
@zxenonx all changes done

2023-10-21 08:08 UTC, Godhanded approved these changes

2023-10-21 08:11 UTC, merged