Refactor endpoint for retrieving all temporarily deleted products
hngx-org/spitfire-super-admin-one pull request #201
Opened 2023-10-20 15:37 UTC by kevinkoech357

​
## Description
Following the resources provided by @zxenonx on standard API naming conventions and best practices, I fixed my endpoint of retrieving all temporarily deleted products by replacing underscores with hyphens. I also updated swagger docs to reflect the same.
​
## Related Issue (Link to linear ticket)

​
## Motivation and Context
Following best API practices.
​
## How Has This Been Tested?
Just an api fix.
​
## Screenshots (if appropriate - Postman, etc):
​
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-10-20 16:30 UTC, zxenonx requested changes
Thanks @kevinkoech357 
I left some comments

2023-10-20 16:30 UTC, zxenonx commented on super_admin_1/products/routes.py
> +@product.route("/temporarily-deleted-products", methods=["GET"])
```suggestion
@product.route("/products?status=soft-deleted", methods=["GET"])
```

2023-10-20 16:30 UTC, zxenonx commented on super_admin_1/products/routes.py
>          JSON response with status and message:
- type hint missing
- proper docstring missing (Kindly check Google Python Style guide - docstring section)

2023-10-20 16:30 UTC, zxenonx commented on swagger_config.yaml
> +  /product/temporarily-deleted-products:
```suggestion
  /products...:
```

2023-10-20 17:13 UTC, kevinkoech357 commented on super_admin_1/products/routes.py
>          JSON response with status and message:
On it.

2023-10-20 18:09 UTC, zxenonx requested changes
Please check again
I think there's a misunderstanding

2023-10-20 18:09 UTC, zxenonx commented on swagger_config.yaml
> +  /products...:
Ah, that's not what I suggested o
Check what how i changed the route....

2023-10-20 19:24 UTC, kevinkoech357 commented on swagger_config.yaml
> +  /products...:
@zxenonx Sorry, I've updated swagger.yaml to reflect the newly suggested route. I hope the issue has now been sorted.

2023-10-21 08:39 UTC, kevinkoech357 commented on super_admin_1/products/routes.py
>          JSON response with status and message:
@zxenonx How about now? Any mistakes?

2023-10-21 10:06 UTC, kevinkoech357 commented
@Freeman-kuch how about this?

2023-10-22 00:37 UTC, closed without merging