Fix: Endpoint Config
hngx-org/spitfire-super-admin-one pull request #222
Opened 2023-10-21 13:50 UTC by KimFarida

​
## Description

​
## Related Issue (Link to linear ticket)

​
## Motivation and Context

​
## How Has This Been Tested?

​
## Screenshots (if appropriate - Postman, etc):
​
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
​
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-21 19:42 UTC, Freeman-kuch requested changes

2023-10-21 19:42 UTC, Freeman-kuch commented on health/endpoints/superadmin_1.py
> +        "url": "/product/approve/{product_id}",
all these endpoints are old

2023-10-21 19:46 UTC, KimFarida commented on health/endpoints/superadmin_1.py
> +        "url": "/product/approve/{product_id}",
I thought i changed it

2023-10-21 19:46 UTC, KimFarida commented on health/endpoints/superadmin_1.py
> +        "url": "/product/approve/{product_id}",
On it

2023-10-22 00:36 UTC, Freeman-kuch approved these changes

2023-10-22 00:37 UTC, merged